services:
  - type: web
    name: villa-romeo-admin
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
